name: playbook-pipeline

on:
  workflow_call:
    inputs:
      run-tests:
        type: boolean
        default: true
      run-analyzer:
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
  analyze:
    if: ${{ inputs.run-analyzer }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Policy Gate
        run: node scripts/policy-gate.js
  test:
    if: ${{ inputs.run-tests }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Test
        run: npm test -- --ci --reporters=default --reporters=jest-junit
