global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9464']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9465']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    # Only scrape if api-gateway is available
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: api-gateway:9465

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:9466']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:9467']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    # Optional: only if you add node-exporter to docker-compose

  # Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    # Optional: only if you add postgres-exporter to docker-compose

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    # Optional: only if you add redis-exporter to docker-compose
